### ISSUE TITLE
New Script: Hiding ~/Documents/Adobe Directory

### ISSUE THREAD

**Issue by walteweiss** [trueowl/Adobe#1]
I am a heavy user of ~/Documents directory, and I have noticed Adobe generates some rubbish there. I moved the directory to another disk, where I keep all the rubbish and redirected it with symbolic link, which I hid with `chflags -h hidden /path/to/the/symlink`. Now I have no Adobe directory there, it doesn't take any space, so I can sync my entire directory with Syncthing. (I know you can add ignore rules there, but I also doesn't want it to take my SSD space, which is quite limited.)

I have just made a very simple script that I am going to add soon.

**Comment by BasilSkrnk** [comment]
I checked the script, it works, but would be great to improve it with interactivity.

I see two possible questions: 
1. Whether a user has the directory already, 
2. And the location to which a user wants to move the directory.

So the script would be universal.
